---
apiVersion: v1
kind: ReplicationController
metadata:
  name: recsvc
spec:
  replicas: 3
  selector:
    app: stm
  template:
    metadata:
      labels:
        app: stm
    spec:
      containers:
        - name: cont2
          image: ayyappaad/dj:stockmarket
          ports:
            - containerPort: 80


---
