---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    env: dev
    client: tcs
    app: newspaper
spec:
  containers:
    - name: mycont1
      image: ayyappaad/dj:cjpnewspaper
      ports:
        - containerPort: 80
